### ISSUE TITLE
undeclared identifiers with Vulkan SDK 1.2.135.0

### ISSUE THREAD

**Issue by rogerallen** [GPSnoopy/RayTracingInVulkan#8]
Thanks for writing this.  It works very nicely.  Using VulkanSDK-1.2.135.0, I get errors on `RayTracingInVulkan\src\Vulkan\DebugUtilsMessenger.cpp` lines 48 & 49.
```
error C2065: 'VK_OBJECT_TYPE_OBJECT_TABLE_NVX': undeclared identifier
error C2065: 'VK_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NVX': undeclared identifier
```
Commenting out these lines allowed my compile to finish & I was able to run the program.

**Comment by GPSnoopy** [comment]
Hi @rogerallen,

Thanks for the heads-up. Looks like experiemental extensions that got dropped or promoted.

I've actually got a branch that works with SDK 1.2.135 (see PR #7). It's transitioning from NVIDIA-specific VK_NV_ray_tracing extension to the vendor neutral VK_KHR_ray_tracing extension. I'm waiting for the extension to be stabilised and available in regular drivers before merging it (for the moment you have to download the NVIDIA Vulkan Developer Beta Drivers to access it).

If it drags, I might fix master independently.

**Comment by GPSnoopy** [comment]
Master has been updated to Vulkan SDK 1.2.135 (not waiting on PR #7).
